name: news
description: A new Flutter project.


publish_to: 'none' 




 








version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  go_router: ^9.0.3
  provider: ^6.0.5
  logger: ^1.4.0
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
   - lang/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
