name: news
description: A new Flutter project.


publish_to: 'none' 




 








version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  go_router: ^11.1.2
  provider: ^6.0.5
  logger: ^2.0.2+1
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  dio: ^5.2.1+1
  line_icons: ^2.0.3
  google_nav_bar: ^5.0.6
  jiffy: ^6.2.1
  url_launcher: ^6.1.14
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  dropdown_search: ^5.0.6
  flutter_native_splash: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
   - lang/
   - images/

flutter_native_splash:
  color: "#f0f0f0"
  color_dark: "#0f0f0f"
  image: images/logo.png

  # android_12:
  #   color: "#f0f0f0"
  #   color_dark: "#0f0f0f"
  #   image: images/logo.png

  fullscreen: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
